generadorDeDatos: generadorDeDatos.o
	gcc $(CFLAGS) -o generadorDeDatos generadorDeDatos.o

generadorDeDatos.o: generadorDeDatos.c
	gcc $(CFLAGS) -c generadorDeDatos.c

clean:
	rm *.o generadorDeDatos